version: 2

models:
  - name: dim_listings
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts')
              field: host_id
      - name: room_type
        tests:
          - accepted_values:
              values: ['Shared room','Private room','Hotel room','Entire home/apt']
